### ISSUE TITLE
Object.defineProperty typo

### ISSUE THREAD

**Issue by acutmore** [seanmorris/Weaker#1]
https://github.com/seanmorris/Weaker/blob/c8b9f3da6746dc05e16f5ee06b451d0231d82fef/weakerset/WeakerSet.mjs#L136

I think the 3rd argument here should be something like: `{ value: ... }`, not the value directly.

**Comment by seanmorris** [comment]
Done and done!

https://github.com/seanmorris/Weaker/blob/c3171113410dfa4b923efeb14872d00935d2b1e1/weakermap/WeakerMap.mjs#L140
