### ISSUE TITLE
WeakerMap `delete` and `clear` should cancel finalisers

### ISSUE THREAD

**Issue by acutmore** [seanmorris/Weaker#2]
https://github.com/seanmorris/Weaker/blob/c3171113410dfa4b923efeb14872d00935d2b1e1/weakermap/WeakerMap.mjs#L23

When `clear` or `delete` is called on a `WeakerMap` instance it should lookup the values being removed and `unregister` them to avoid the callback removing a different value which gets subsequently added with the same key.

An alternative for `clear` would be to create a new `FinilizationRegistry`, and the callback only removes the key if the maps current `registry` is still set to itself.

**Comment by seanmorris** [comment]
@acutmore I was thinking about this one, but the keys _are_ the weak-references in this scenario, so if a new value is added with the same key, and that key is removed, then it should still be cleaned up.

**Comment by seanmorris** [comment]
My brain is fried today after Emscripten stuff. Looking at this now.

**Comment by seanmorris** [comment]
Done and done.

https://github.com/seanmorris/Weaker/blob/27ddf946ec4c3478824849886d8ce7044ee4175c/weakermap/WeakerMap.mjs#L1-L17

https://github.com/seanmorris/Weaker/blob/27ddf946ec4c3478824849886d8ce7044ee4175c/weakermap/WeakerMap.mjs#L34-L49
